### ISSUE TITLE
SSL/TLS connection when loading  default layout

### ISSUE THREAD

**Issue by davisthegreate** [qmk/qmk_toolbox#73]
OS: Windows 10

OS Version:   1903 18362.113

QMK Toolbox version: 0.0.9.0

Issue description: 

I receive an UNhandled exception error - the request was aborted: Could not create SSL/TLS secure channel when trying to load default hex layouts

QMK Toolbox log:

ee the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at QMK_Toolbox.Form1.setFilePath(String filepath)
   at QMK_Toolbox.Form1.loadKeymap_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3801.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
qmk_toolbox
    Assembly Version:    ###0.0.9.0
    Win32 Version: 0.0.9.net

**Comment by drashna** [comment]
redownload the file, it should fix the issue.
